### ISSUE TITLE
rooftop-survivors.zip is missing

### ISSUE THREAD

**Issue by daisy-ycguo** [IBM/drones-iot-visual-recognition#11]
But it is mentioned at [FLOODING.md](https://github.com/IBM/drones-iot-visual-recognition/blob/master/Flooding/FLOODING.md#step-2---capturing-images)

**Comment by stevemar** [comment]
@johnwalicki can you either add the missing zip file or remove that class from the flooding.md instructions?

**Comment by johnwalicki** [comment]
@daisy-ycguo  Flooding instructions and zip files have been pushed to this repo.
