### ISSUE TITLE
IBM Cloud signup does not return you to the lab

### ISSUE THREAD

**Issue by jkomg** [IBM/drones-iot-visual-recognition#9]
under Prereqs when you leave to go to https://console.bluemix.net/registration to create a Cloud account, there's no way to return to the lab without manually going back. 

(this is being fixed, I think)

**Comment by stevemar** [comment]
One way to fix this would be to add some in-line html to open in a new tab, it'll looks like the snippet below. I'm not totally for this approach as the syntax is not intuitive and I don't want ibm devs to get into that habit of adding HTML in our READMEs:

```
[go](http://stackoverflow.com){:target="_blank"}.
```

In general, I think most folks are OK with having to right-click most links and click 'Open in new tab'.
